# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: id_rsa
        if_key_exists: replace
        known_hosts: unnecessary
        
    - run: |
        ssh-keyscan -H gitee.com > /home/runner/.ssh/known_hosts
        git config --global user.email "hi@typora.io"
        git config --global user.name "Typora"
        git remote add gitee git@gitee.com:typora-mirror/typora-theme-gallery.git
        git push -f gitee gh-pages
